//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamiento.ServiceEstacionamiento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEstacionamiento.crudEstacionamientoSoap")]
    public interface crudEstacionamientoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento comuna del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEstacionamiento", ReplyAction="*")]
        Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoResponse InsertEstacionamiento(Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEstacionamiento", ReplyAction="*")]
        System.Threading.Tasks.Task<Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoResponse> InsertEstacionamientoAsync(Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEstacionamientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEstacionamiento", Namespace="http://tempuri.org/", Order=0)]
        public Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequestBody Body;
        
        public InsertEstacionamientoRequest() {
        }
        
        public InsertEstacionamientoRequest(Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEstacionamientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string comuna;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string comentario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string auto;
        
        public InsertEstacionamientoRequestBody() {
        }
        
        public InsertEstacionamientoRequestBody(string comuna, string direccion, string comentario, int id, int valor, string auto) {
            this.comuna = comuna;
            this.direccion = direccion;
            this.comentario = comentario;
            this.id = id;
            this.valor = valor;
            this.auto = auto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEstacionamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEstacionamientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoResponseBody Body;
        
        public InsertEstacionamientoResponse() {
        }
        
        public InsertEstacionamientoResponse(Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEstacionamientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertEstacionamientoResult;
        
        public InsertEstacionamientoResponseBody() {
        }
        
        public InsertEstacionamientoResponseBody(bool InsertEstacionamientoResult) {
            this.InsertEstacionamientoResult = InsertEstacionamientoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface crudEstacionamientoSoapChannel : Estacionamiento.ServiceEstacionamiento.crudEstacionamientoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class crudEstacionamientoSoapClient : System.ServiceModel.ClientBase<Estacionamiento.ServiceEstacionamiento.crudEstacionamientoSoap>, Estacionamiento.ServiceEstacionamiento.crudEstacionamientoSoap {
        
        public crudEstacionamientoSoapClient() {
        }
        
        public crudEstacionamientoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public crudEstacionamientoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public crudEstacionamientoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public crudEstacionamientoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoResponse Estacionamiento.ServiceEstacionamiento.crudEstacionamientoSoap.InsertEstacionamiento(Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequest request) {
            return base.Channel.InsertEstacionamiento(request);
        }
        
        public bool InsertEstacionamiento(string comuna, string direccion, string comentario, int id, int valor, string auto) {
            Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequest inValue = new Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequest();
            inValue.Body = new Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequestBody();
            inValue.Body.comuna = comuna;
            inValue.Body.direccion = direccion;
            inValue.Body.comentario = comentario;
            inValue.Body.id = id;
            inValue.Body.valor = valor;
            inValue.Body.auto = auto;
            Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoResponse retVal = ((Estacionamiento.ServiceEstacionamiento.crudEstacionamientoSoap)(this)).InsertEstacionamiento(inValue);
            return retVal.Body.InsertEstacionamientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoResponse> Estacionamiento.ServiceEstacionamiento.crudEstacionamientoSoap.InsertEstacionamientoAsync(Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequest request) {
            return base.Channel.InsertEstacionamientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoResponse> InsertEstacionamientoAsync(string comuna, string direccion, string comentario, int id, int valor, string auto) {
            Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequest inValue = new Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequest();
            inValue.Body = new Estacionamiento.ServiceEstacionamiento.InsertEstacionamientoRequestBody();
            inValue.Body.comuna = comuna;
            inValue.Body.direccion = direccion;
            inValue.Body.comentario = comentario;
            inValue.Body.id = id;
            inValue.Body.valor = valor;
            inValue.Body.auto = auto;
            return ((Estacionamiento.ServiceEstacionamiento.crudEstacionamientoSoap)(this)).InsertEstacionamientoAsync(inValue);
        }
    }
}
