//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamiento.ServiceInfo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInfo.crudInfoSoap")]
    public interface crudInfoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistraResena", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RegistraResena(int puntaje, string comentario, int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistraResena", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegistraResenaAsync(int puntaje, string comentario, int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistraDenuncia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RegistraDenuncia(string descripcion, int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistraDenuncia", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegistraDenunciaAsync(string descripcion, int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminaResena", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EliminaResena(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminaResena", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminaResenaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminaDenuncia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EliminaDenuncia(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminaDenuncia", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminaDenunciaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaResenas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListaResenas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaResenas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListaResenasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDenuncia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListaDenuncia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDenuncia", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListaDenunciaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface crudInfoSoapChannel : Estacionamiento.ServiceInfo.crudInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class crudInfoSoapClient : System.ServiceModel.ClientBase<Estacionamiento.ServiceInfo.crudInfoSoap>, Estacionamiento.ServiceInfo.crudInfoSoap {
        
        public crudInfoSoapClient() {
        }
        
        public crudInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public crudInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public crudInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public crudInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistraResena(int puntaje, string comentario, int id_usuario) {
            return base.Channel.RegistraResena(puntaje, comentario, id_usuario);
        }
        
        public System.Threading.Tasks.Task<bool> RegistraResenaAsync(int puntaje, string comentario, int id_usuario) {
            return base.Channel.RegistraResenaAsync(puntaje, comentario, id_usuario);
        }
        
        public bool RegistraDenuncia(string descripcion, int id_usuario) {
            return base.Channel.RegistraDenuncia(descripcion, id_usuario);
        }
        
        public System.Threading.Tasks.Task<bool> RegistraDenunciaAsync(string descripcion, int id_usuario) {
            return base.Channel.RegistraDenunciaAsync(descripcion, id_usuario);
        }
        
        public bool EliminaResena(int id) {
            return base.Channel.EliminaResena(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaResenaAsync(int id) {
            return base.Channel.EliminaResenaAsync(id);
        }
        
        public bool EliminaDenuncia(int id) {
            return base.Channel.EliminaDenuncia(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaDenunciaAsync(int id) {
            return base.Channel.EliminaDenunciaAsync(id);
        }
        
        public System.Data.DataSet ListaResenas() {
            return base.Channel.ListaResenas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListaResenasAsync() {
            return base.Channel.ListaResenasAsync();
        }
        
        public System.Data.DataSet ListaDenuncia() {
            return base.Channel.ListaDenuncia();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListaDenunciaAsync() {
            return base.Channel.ListaDenunciaAsync();
        }
    }
}
