//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estacionamiento.ServiceUsuario {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.crudUsuarioSoap")]
    public interface crudUsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListaUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListaUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IniciarSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IniciarSesion(string correo_usuario, string contrasena_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IniciarSesion", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(string correo_usuario, string contrasena_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaExistencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidaExistencia(string correo_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaExistencia", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ValidaExistenciaAsync(string correo_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompruebaArrendador_Duenno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CompruebaArrendador_Duenno(int id_usuario, int id_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompruebaArrendador_Duenno", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CompruebaArrendador_DuennoAsync(int id_usuario, int id_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompruebaArrendador_DuennoWithCorreo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CompruebaArrendador_DuennoWithCorreo(string correo, int id_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CompruebaArrendador_DuennoWithCorreo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CompruebaArrendador_DuennoWithCorreoAsync(string correo, int id_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiaEstado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CambiaEstado(int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiaEstado", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CambiaEstadoAsync(int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CreaUsuario(string nombre_usuario, string apellido_usuario, string rut_usuario, string contrasena_usuario, int estado_usuario, string correo_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreaUsuarioAsync(string nombre_usuario, string apellido_usuario, string rut_usuario, string contrasena_usuario, int estado_usuario, string correo_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaUsuario_Tipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertaUsuario_Tipo(int id_usuario, int id_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertaUsuario_Tipo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> InsertaUsuario_TipoAsync(int id_usuario, int id_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Estacionamiento.ServiceUsuario.User GetUser(string emailAddress, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Estacionamiento.ServiceUsuario.User> GetUserAsync(string emailAddress, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserWithoutTipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Estacionamiento.ServiceUsuario.User GetUserWithoutTipo(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserWithoutTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<Estacionamiento.ServiceUsuario.User> GetUserWithoutTipoAsync(string emailAddress);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_usuarioField;
        
        private string nombre_usuarioField;
        
        private string apellido_usuarioField;
        
        private string rut_usuarioField;
        
        private string contrasena_usuarioField;
        
        private int estado_usuarioField;
        
        private string correo_usuarioField;
        
        private string imagen_usuarioField;
        
        private int tipo_usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                this.id_usuarioField = value;
                this.RaisePropertyChanged("id_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombre_usuario {
            get {
                return this.nombre_usuarioField;
            }
            set {
                this.nombre_usuarioField = value;
                this.RaisePropertyChanged("nombre_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string apellido_usuario {
            get {
                return this.apellido_usuarioField;
            }
            set {
                this.apellido_usuarioField = value;
                this.RaisePropertyChanged("apellido_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string rut_usuario {
            get {
                return this.rut_usuarioField;
            }
            set {
                this.rut_usuarioField = value;
                this.RaisePropertyChanged("rut_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string contrasena_usuario {
            get {
                return this.contrasena_usuarioField;
            }
            set {
                this.contrasena_usuarioField = value;
                this.RaisePropertyChanged("contrasena_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int estado_usuario {
            get {
                return this.estado_usuarioField;
            }
            set {
                this.estado_usuarioField = value;
                this.RaisePropertyChanged("estado_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string correo_usuario {
            get {
                return this.correo_usuarioField;
            }
            set {
                this.correo_usuarioField = value;
                this.RaisePropertyChanged("correo_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string imagen_usuario {
            get {
                return this.imagen_usuarioField;
            }
            set {
                this.imagen_usuarioField = value;
                this.RaisePropertyChanged("imagen_usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int tipo_usuario {
            get {
                return this.tipo_usuarioField;
            }
            set {
                this.tipo_usuarioField = value;
                this.RaisePropertyChanged("tipo_usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface crudUsuarioSoapChannel : Estacionamiento.ServiceUsuario.crudUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class crudUsuarioSoapClient : System.ServiceModel.ClientBase<Estacionamiento.ServiceUsuario.crudUsuarioSoap>, Estacionamiento.ServiceUsuario.crudUsuarioSoap {
        
        public crudUsuarioSoapClient() {
        }
        
        public crudUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public crudUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public crudUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public crudUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListaUsuarios() {
            return base.Channel.ListaUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListaUsuariosAsync() {
            return base.Channel.ListaUsuariosAsync();
        }
        
        public bool IniciarSesion(string correo_usuario, string contrasena_usuario) {
            return base.Channel.IniciarSesion(correo_usuario, contrasena_usuario);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(string correo_usuario, string contrasena_usuario) {
            return base.Channel.IniciarSesionAsync(correo_usuario, contrasena_usuario);
        }
        
        public bool ValidaExistencia(string correo_usuario) {
            return base.Channel.ValidaExistencia(correo_usuario);
        }
        
        public System.Threading.Tasks.Task<bool> ValidaExistenciaAsync(string correo_usuario) {
            return base.Channel.ValidaExistenciaAsync(correo_usuario);
        }
        
        public bool CompruebaArrendador_Duenno(int id_usuario, int id_tipo) {
            return base.Channel.CompruebaArrendador_Duenno(id_usuario, id_tipo);
        }
        
        public System.Threading.Tasks.Task<bool> CompruebaArrendador_DuennoAsync(int id_usuario, int id_tipo) {
            return base.Channel.CompruebaArrendador_DuennoAsync(id_usuario, id_tipo);
        }
        
        public bool CompruebaArrendador_DuennoWithCorreo(string correo, int id_tipo) {
            return base.Channel.CompruebaArrendador_DuennoWithCorreo(correo, id_tipo);
        }
        
        public System.Threading.Tasks.Task<bool> CompruebaArrendador_DuennoWithCorreoAsync(string correo, int id_tipo) {
            return base.Channel.CompruebaArrendador_DuennoWithCorreoAsync(correo, id_tipo);
        }
        
        public bool CambiaEstado(int id_usuario) {
            return base.Channel.CambiaEstado(id_usuario);
        }
        
        public System.Threading.Tasks.Task<bool> CambiaEstadoAsync(int id_usuario) {
            return base.Channel.CambiaEstadoAsync(id_usuario);
        }
        
        public bool CreaUsuario(string nombre_usuario, string apellido_usuario, string rut_usuario, string contrasena_usuario, int estado_usuario, string correo_usuario) {
            return base.Channel.CreaUsuario(nombre_usuario, apellido_usuario, rut_usuario, contrasena_usuario, estado_usuario, correo_usuario);
        }
        
        public System.Threading.Tasks.Task<bool> CreaUsuarioAsync(string nombre_usuario, string apellido_usuario, string rut_usuario, string contrasena_usuario, int estado_usuario, string correo_usuario) {
            return base.Channel.CreaUsuarioAsync(nombre_usuario, apellido_usuario, rut_usuario, contrasena_usuario, estado_usuario, correo_usuario);
        }
        
        public bool InsertaUsuario_Tipo(int id_usuario, int id_tipo) {
            return base.Channel.InsertaUsuario_Tipo(id_usuario, id_tipo);
        }
        
        public System.Threading.Tasks.Task<bool> InsertaUsuario_TipoAsync(int id_usuario, int id_tipo) {
            return base.Channel.InsertaUsuario_TipoAsync(id_usuario, id_tipo);
        }
        
        public Estacionamiento.ServiceUsuario.User GetUser(string emailAddress, string pass) {
            return base.Channel.GetUser(emailAddress, pass);
        }
        
        public System.Threading.Tasks.Task<Estacionamiento.ServiceUsuario.User> GetUserAsync(string emailAddress, string pass) {
            return base.Channel.GetUserAsync(emailAddress, pass);
        }
        
        public Estacionamiento.ServiceUsuario.User GetUserWithoutTipo(string emailAddress) {
            return base.Channel.GetUserWithoutTipo(emailAddress);
        }
        
        public System.Threading.Tasks.Task<Estacionamiento.ServiceUsuario.User> GetUserWithoutTipoAsync(string emailAddress) {
            return base.Channel.GetUserWithoutTipoAsync(emailAddress);
        }
    }
}
